version: '3.8'

networks:
  earthbit:
    driver: bridge

services:
  manager:
    build: ./manager
    container_name: sun-manager
    environment:
      - ROLE=manager
      - USE_DHCLIENT=0
      - ELECTION_INTERVAL=10
      - ELECTION_K=1
    ports:
      - "8888:8888"
    networks:
      - earthbit
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  worker1:
    build: ./worker
    container_name: moon-worker-1
    environment:
      - ROLE=worker
      - USE_DHCLIENT=0
      - MANAGER_HOST=manager
    networks:
      - earthbit
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  worker2:
    build: ./worker
    container_name: moon-worker-2
    environment:
      - ROLE=worker
      - USE_DHCLIENT=0
      - MANAGER_HOST=manager
    networks:
      - earthbit
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3


